name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run app (simulated deploy)
        run: |
          echo "Deploying FastAPI app..."
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
